### PR TITLE
[IO3] After presentation changes

### PR DESCRIPTION
**Pull request by snapeeek**
DriverCommandCounterVisitor now works on current command
Access modifiers changed mostly to private

### CODE REVIEW

**Comment by snapeeek** [comment]
+ deleted unnecessary imports

**Comment by kowallus** [comment]
Nice, but there are some conflicts (due to other PRs)

**Comment by snapeeek** [comment]
I can't resolve them now because GitHub has some problems

**Comment by snapeeek** [comment]
To be honest: I don't even know what happened. GitHub wanted to create new branch on our forked repository, but it looks like it was created on main repo. Now when I try to resolve conflict at GitHub site I get pop-up that site is out of date, and to start over. Now I am in a constant loop of out of date sites

**Comment by snapeeek** [comment]
I think I need to create new pull request

**Comment by kowallus** [comment]
Maybe try fetch and pull remote changes on every branch.

**Comment by kowallus** [comment]
The issue with branches and merging seems to be too complicated. I am closing the PR and we can forget about it ;).

**Pull request closed without merging**
